=head1 PHP Couchbase Tests

This is an extensive testsuite for the PHP couchbase client. This is a
work in progress to convert existing tests into the new format.

=head2 Layout

Currently there are tests in both C<tests> and C<unit>, where the former are the
legacy phpt-style tests, and the latter are the new tests utilizing
L<PHPUnit|https://github.com/sebastianbergmann/phpunit>

=head2 Usage

I removed the documentation for the phpt tests since they are wrong, and weird to
set up.

For the new-style tests, you should chdir into the C<unit> directory.
You will need to edit the C<couchbase.local.inc> with your cluster parameters
(testing against a mock server is not yet supported)..

and run something like

    # set LD_LIBRARY_PATH if you are testing against a libcouchbase not in the
    # standard linker search path
	# LD_LIBRARY_PATH=/sources/lcb2.0-repo/install

	EXTDIR=~/src/php-ext-couchbase
    export EXTDIR
    export LD_LIBRARY_PATH

	./pwrap.sh --debug -c test.xml

You need to have C<PHPUnit> installed for the new tests. Debian includes a C<phpunit>
package. It can also be obtained via PEAR (see https://github.com/sebastianbergmann/phpunit#installation
for instructions).

the C<pwrap.sh> script is a wrapper around the C<phpunit> executable,
which sets up the appropriate locations for finding the couchbase extension

On Darwin/OS X systems, the environment variable is C<DYLD_LIBRARY_PATH>.

=head2 Goodies

There is a C<cbc>-like program located in C<utils>. Run
    
    ./pcbc help

For more information.

The C<EXTDIR> variable must be set for this program as well, as per the C<pwrap.sh> script


M. Nunberg
